services:
  caddy:
    build: .
    container_name: caddy
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --watch
    environment:
      - CLOUDFLARE_API_TOKEN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - roast-roulette_media:/srv/media/django:ro
      - website_dist:/srv/website:ro
      - game_web:/srv/game:ro
    restart: always

volumes:
  roast-roulette_media:
    external: true
  caddy_data:
  caddy_config:
  website_dist:
  game_web:

networks:
  default:
    name: proxy
    external: true
