services:
  caddy:
    build: .
    container_name: caddy
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --watch
    environment:
      - CLOUDFLARE_API_TOKEN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./data:/data
      - ./config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - roast-roulette_media:/srv/media/django:ro
      - /home/chris/website/dist:/srv/website:ro
      - /home/chris/game/web:/srv/game:ro
    restart: always

volumes:
  roast-roulette_media:
    external: true

networks:
  default:
    name: proxy
    external: true
