services:
  sonarr:
    image: ghcr.io/hotio/sonarr:release
    container_name: sonarr
    environment:
      PUID: "1000"
      PGID: "100"
      TZ: Europe/Bucharest
      UMASK: "002"
    expose: [ 8989 ]
    volumes:
      - sonarr_config:/config
      - /mnt/nas/media_server:/data
    networks: [ proxy, default ]
    restart: unless-stopped

volumes:
  sonarr_config:

networks:
  proxy:
    external: true
