services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    expose: [ 80 ]
    networks:
      - proxy
      - default
    volumes:
      - vaultwarden_data:/data
    environment:
      - ADMIN_TOKEN=admin
      - DOMAIN=https://vault.christiantanul.com
      - SIGNUPS_ALLOWED=true

volumes:
  vaultwarden_data:

networks:
  proxy:
    external: true
