#cloud-config
# Bootstrap configuration for Synology VM

hostname: vm
manage_etc_hosts: true

# User setup
users:
  - name: chris
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUJWuWXCZpiPQSwRZgOU6baccQZ14+lTJqUeMtfNE1jZcvtucF++3S7CTH7mHngFbI71/Io+ICqEZAkYBnu72CMwPXOwFyj5nerhQK5uX6KWGcLMXYwH4v43jWVdv/Xe/Dk3xshD3yevgeGzgQZxmWlko6hgr+0sGU7eJBFbfx8ILKTOLbXSVyBCx5xK37vaa8x7ZUB7oASj0hLH6YXs+BjPpwQuXCnNx8exMwMWajfaJ5gqaIyZLxyXJxgt8gbMTeQNN8fbavxiZozWwFbC50kXcHR8lKsGvXgqA5WlU55RdYoEzSTWflw6bsyEaFNbXBt2asAVDNBMPS1/aP8vdlKolU1Sqd/dMFYu1WLQ+Q705G//+iwEWeiZpg/m9+8CSU6OD0toRaUneC11CmDXTJjS89giIbofpz900+j2WOcSbAOEGHjCEl+qDl4bWXndF9itqgblQjFDysgJ3ZI4PAR4OCB8GyNY5UUoKg2HAB8H50gNdV0pHS2ysPh8c3Me/cGfbBYVUjzzsmxEd4VGzCP098ippMpgK/K/Q9TFtuaxEZZ3jOb0/GU10JjatgWYfULzXyXRkyptZDkGyGR+6I0YfcEmFy8hInf1oXS8keDHGAxznXn3EhNXH6xQuaJM4zIOE60CUUdBC3Iz1T7Kmidc9BNDGz/ggJmnD66RzTBw=="
    groups: [docker, sudo]

# Network configuration
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses: [192.168.0.100/24]
      gateway4: 192.168.0.1

# System packages (minimal - only bootstrap essentials)
packages:
  - docker.io
  - openssh-server
  - curl
  - git
  - build-essential

package_update: true
package_upgrade: true

# System setup
runcmd:
  # Configure services
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker chris
  - systemctl enable ssh
  
  # Install Nix
  - su - chris -c 'sh <(curl -L https://nixos.org/nix/install) --no-daemon'
  - su - chris -c 'mkdir -p /home/chris/.config/nix'
  - su - chris -c 'echo "experimental-features = nix-command flakes" > /home/chris/.config/nix/nix.conf'
  
  # Setup homelab environment
  - su - chris -c 'git clone https://github.com/scriptogre/homelab.git /home/chris/.homelab'
  - su - chris -c 'cd /home/chris/.homelab && nix run home-manager/master -- switch --flake .#chris@vm'
  
  # Initialize Docker Swarm
  - su - chris -c 'docker swarm init --advertise-addr 192.168.0.100'
  - su - chris -c 'docker node update --label-add location=local --label-add type=manager $(hostname)'
  
  # Change shell to zsh
  - chsh -s /bin/zsh chris

final_message: |
  🎉 VM ready!
  
  Access: ssh chris@192.168.0.100
  
  Next steps:
  1. Setup Tailscale: sudo tailscale up --advertise-routes=192.168.0.0/24 --accept-routes
  2. Clone services repo: git clone https://github.com/scriptogre/services.git
  3. Deploy services as needed